-- ADR 0001 §1 — durability schema. AUTHORITATIVE.
--
-- Per docs/durability-harness-plan.md, this file — not the ADR prose — is the source of
-- SQL truth. The ADR presents its DDL in reading order and says so; this file is in
-- dependency order so it loads into an empty database in one pass. Where this file and
-- the ADR disagree, this file is right and the ADR is amended.
--
-- Deviations from ADR 0001 §1, each deliberate:
--   1. Ordering: run_key precedes search_job (§1's own NB), provider_run precedes outbox.
--   2. `performance` is defined here. B5(c) and B6 both write it and §1 never declares it,
--      so the SCHEDULE_RESOLUTION acceptance branch could not execute at all. Shape is
--      minimal and deliberately not a product schema: it carries only what the schedule
--      branch of acceptance needs (the key it resolved, the showtimes it produced, the
--      observation that produced them).
--   3. Partitions live in 002, generated by a function rather than frozen to 2026-08.
--
-- Postgres 16. All IDs are text ULIDs unless noted; timestamptz throughout; enum-like
-- columns are text + CHECK.

CREATE TABLE search (
  search_id          text PRIMARY KEY,
  session_id         text NOT NULL,
  idempotency_key    text NOT NULL,
  spec               jsonb NOT NULL,
  spec_hash          text NOT NULL,
  status             text NOT NULL DEFAULT 'PENDING_SCHEDULE'
                     CHECK (status IN ('PENDING_SCHEDULE','RUNNING',
                                       'COMPLETE','PARTIAL','HALTED')),
  terminal_cause     text,                 -- derived in B8, never caller-supplied
  -- persisted admission-denial fact (B6 stage-2 reject). Without a durable record,
  -- B8 has nothing to derive HALTED/CAPACITY from.
  capacity_denied_at timestamptz,
  -- NB: schedule outcome is PER SUBSCRIPTION (run_subscription.schedule_outcome),
  -- not a single column here — a search may own N schedule runs (§14.1 item 3).
  deadline_at        timestamptz NOT NULL,
  projected_through  bigint NOT NULL DEFAULT 0,  -- event-projector watermark (B10)
  -- §4.1 coalescing aggregation counters
  agg_requested_rev  bigint NOT NULL DEFAULT 0,
  agg_processed_rev  bigint NOT NULL DEFAULT 0,
  agg_lease_expires  timestamptz,          -- advisory claim, serializes AGGREGATE per search
  agg_generation     integer NOT NULL DEFAULT 0,
  -- gapless per-search event seq allocated from this row (§3)
  next_seq           bigint NOT NULL DEFAULT 0,
  created_at         timestamptz NOT NULL DEFAULT now(),
  terminalized_at    timestamptz,
  UNIQUE (session_id, idempotency_key)
);
CREATE INDEX search_nonterminal_deadline
  ON search (deadline_at)
  WHERE status IN ('PENDING_SCHEDULE','RUNNING');

-- §4.4: the key is permanent; a run is a full state machine per attempt.
-- One polymorphic family covers FetchRun and ScheduleRun.
CREATE TABLE run_key (
  run_key_id  text PRIMARY KEY,            -- DETERMINISTIC: hash(kind, provider_id, parts)
  kind        text NOT NULL CHECK (kind IN ('SHOWTIME_FETCH','SCHEDULE_RESOLUTION')),
  provider_id text NOT NULL,
  -- persisted so the §4.3 scoped fence is derivable from the fenced run rather than
  -- supplied by the caller; enforced to agree with kind
  route_class text NOT NULL CHECK (route_class IN ('seat','schedule')),
  CHECK ((kind = 'SHOWTIME_FETCH') = (route_class = 'seat')),
  showtime_id text,                        -- SHOWTIME_FETCH only
  theatre_id  text,                        -- SCHEDULE_RESOLUTION only
  local_date  date,                        -- SCHEDULE_RESOLUTION only
  accepted_revision  bigint NOT NULL DEFAULT 0,  -- monotonic; cache-projection ordering
  projected_revision bigint NOT NULL DEFAULT 0,  -- snapshot-projector watermark (B10):
                                                 -- projected_revision < accepted_revision
                                                 -- IS the durable projection work record
  latest_observation_id text,
  latest_captured_at    timestamptz,       -- freshness gate input; data, not identity
  CHECK (projected_revision <= accepted_revision),
  CHECK (
    (kind = 'SHOWTIME_FETCH'
       AND showtime_id IS NOT NULL AND theatre_id IS NULL AND local_date IS NULL)
    OR
    (kind = 'SCHEDULE_RESOLUTION'
       AND showtime_id IS NULL AND theatre_id IS NOT NULL AND local_date IS NOT NULL)
  ),
  UNIQUE (run_key_id, kind)                -- FK target for search_job's kind agreement
);
CREATE UNIQUE INDEX run_key_fetch ON run_key (provider_id, showtime_id)
  WHERE kind = 'SHOWTIME_FETCH';
CREATE UNIQUE INDEX run_key_schedule ON run_key (provider_id, theatre_id, local_date)
  WHERE kind = 'SCHEDULE_RESOLUTION';

CREATE TABLE search_job (
  job_id           text PRIMARY KEY,       -- ULID fixed at creation: idempotency key
  search_id        text NOT NULL REFERENCES search,
  -- AGGREGATE is deliberately NOT a job kind: it is a claim on the search row (B7).
  kind             text NOT NULL CHECK (kind IN
                     ('SCHEDULE_RESOLUTION','SHOWTIME_FETCH')),
  run_key_id       text NOT NULL,          -- the key this job subscribes to
  generation       integer NOT NULL DEFAULT 0,   -- fencing token; bumped on every re-lease
  state            text NOT NULL DEFAULT 'PENDING' CHECK (state IN
                     ('PENDING','LEASED','DONE','FAILED','CANCELLED')),
  lease_expires_at timestamptz,
  attempt          integer NOT NULL DEFAULT 0,
  deadline_at      timestamptz NOT NULL,
  fail_cause       text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  -- job kind must equal its key's kind — enforced, not assumed
  FOREIGN KEY (run_key_id, kind) REFERENCES run_key (run_key_id, kind),
  -- FK target for run_subscription's composite FK
  UNIQUE (job_id, search_id, run_key_id)
);
CREATE INDEX job_live_by_search ON search_job (search_id)
  WHERE state IN ('PENDING','LEASED');
CREATE INDEX job_sweeper ON search_job (lease_expires_at)
  WHERE state = 'LEASED';
CREATE INDEX job_rearm ON search_job (created_at)
  WHERE state = 'PENDING';

CREATE TABLE provider_run (
  run_id           text PRIMARY KEY,
  run_key_id       text NOT NULL REFERENCES run_key,
  observation_id   text NOT NULL,          -- ULID fixed BEFORE upstream dispatch (§4.1)
  state            text NOT NULL DEFAULT 'PENDING' CHECK (state IN
                     ('PENDING','LEASED','DONE','FAILED','CANCELLED')),
  generation       integer NOT NULL DEFAULT 0,
  lease_expires_at timestamptz,
  attempt          integer NOT NULL DEFAULT 0,
  provider_epoch   bigint NOT NULL,        -- refreshed by the B4 pre-dispatch transition
  fail_cause       text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (run_id, run_key_id)              -- FK target for observation pairing
);
-- §4.4: at most one non-terminal run per key
CREATE UNIQUE INDEX one_live_run_per_key ON provider_run (run_key_id)
  WHERE state IN ('PENDING','LEASED');
CREATE INDEX run_sweeper ON provider_run (lease_expires_at) WHERE state = 'LEASED';

-- Both search_job and provider_run own outbox records, so the target must be
-- discriminated and FK-enforced.
CREATE TABLE outbox (
  outbox_id       text PRIMARY KEY,
  target_kind     text NOT NULL CHECK (target_kind IN ('JOB','RUN')),
  job_id          text REFERENCES search_job (job_id),
  run_id          text REFERENCES provider_run (run_id),
  state           text NOT NULL DEFAULT 'PENDING'
                  CHECK (state IN ('PENDING','PUBLISHED')),
  attempt         integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  CHECK ((target_kind = 'JOB') = (job_id IS NOT NULL)),
  CHECK ((target_kind = 'RUN') = (run_id  IS NOT NULL))
);
-- broker dedup/idempotency key is coalesce(job_id, run_id), unique per target
CREATE INDEX outbox_pending ON outbox (created_at) WHERE state = 'PENDING';
-- Alarm: min(created_at) WHERE state='PENDING' older than 30 s (§4.1)

CREATE TABLE search_event (
  search_id  text NOT NULL REFERENCES search,
  seq        bigint NOT NULL,              -- per-search monotonic, GAPLESS
  type       text NOT NULL,
  payload    jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (search_id, seq)
);
-- no per-row `projected` flag: the watermark on search.projected_through is resettable (B10)

CREATE TABLE run_subscription (
  run_key_id  text NOT NULL REFERENCES run_key,
  search_id   text NOT NULL REFERENCES search,
  job_id      text NOT NULL,
  state       text NOT NULL DEFAULT 'LIVE' CHECK (state IN
                ('LIVE','SATISFIED','EXPIRED','CANCELLED')),
  deadline_at timestamptz NOT NULL,        -- subscriber-specific, never the run's (§4.4)
  -- three-valued schedule outcome, per (search, schedule key)
  schedule_outcome text CHECK (schedule_outcome IN
                     ('RESOLVED','EMPTY_RESOLVED','FAILED')),
  -- per-key unresolved-schedule slot; a search-wide flag cannot express N schedule keys
  admission_counted boolean NOT NULL DEFAULT false,
  PRIMARY KEY (run_key_id, search_id),
  -- the job must belong to THIS search AND subscribe to THIS key
  FOREIGN KEY (job_id, search_id, run_key_id)
    REFERENCES search_job (job_id, search_id, run_key_id)
);
CREATE INDEX sub_live_by_key ON run_subscription (run_key_id) WHERE state = 'LIVE';

-- idempotent per-subscriber application record (§4.4)
CREATE TABLE run_application (
  run_id     text NOT NULL REFERENCES provider_run,
  search_id  text NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (run_id, search_id)
);

-- Observation identity lives in a NON-partitioned registry: Postgres requires every
-- unique constraint on a partitioned table to contain the partition key, and adding
-- captured_at to the key would destroy the property we need (a retry reuses its
-- observation_id but recomputes captured_at).
CREATE TABLE observation (
  observation_id text PRIMARY KEY,         -- ULID fixed BEFORE dispatch (§4.1)
  run_key_id     text NOT NULL REFERENCES run_key,
  run_id         text NOT NULL,
  captured_at    timestamptz NOT NULL,
  accepted_revision bigint NOT NULL,
  -- at most one accepted observation per run, and the run/key pairing is enforced (T24)
  UNIQUE (run_id),
  FOREIGN KEY (run_id, run_key_id) REFERENCES provider_run (run_id, run_key_id)
);

CREATE TABLE availability_snapshot (       -- SHOWTIME_FETCH observations only
  observation_id text NOT NULL REFERENCES observation (observation_id),
  showtime_id    text NOT NULL,
  captured_at    timestamptz NOT NULL,     -- partition key; freshness/ordering data
  bitmap         bytea NOT NULL,
  free_count     integer NOT NULL,
  PRIMARY KEY (observation_id, captured_at)   -- contains the partition key
) PARTITION BY RANGE (captured_at);        -- monthly partitions (§5), created in 002
CREATE INDEX snapshot_freshness ON availability_snapshot (showtime_id, captured_at DESC);

-- SCHEDULE_RESOLUTION observations. NOT IN ADR 0001 §1 — added here because B5(c)'s
-- schedule branch and B6's expansion both write it, so without it the schedule half of
-- the state machine cannot execute. Scope is deliberately narrow: this is the durable
-- record of "which showtimes this schedule key resolved to", not the product's showtime
-- model. Product columns (movie, format, price basis) land when the query design's
-- Performance shape is settled; nothing in ADR 0001 depends on them.
CREATE TABLE performance (
  showtime_id    text PRIMARY KEY,         -- provider-scoped showtime identity
  provider_id    text NOT NULL,
  theatre_id     text NOT NULL,
  local_date     date NOT NULL,
  starts_at      timestamptz NOT NULL,
  observation_id text NOT NULL REFERENCES observation (observation_id),
  attributes     jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX performance_by_schedule_key
  ON performance (provider_id, theatre_id, local_date);

-- §4.3 provider halt epochs. The FENCE is a single provider-wide scalar, deliberately
-- separated from the scoped state rows: with per-row epochs a route halt leaves
-- max(epoch) unchanged and a stale observation passes the fence.
CREATE TABLE provider_fence (
  provider_id text PRIMARY KEY,
  epoch       bigint NOT NULL DEFAULT 0
);

-- scoped rows carry state only; route_class '' = provider-wide (wins when stricter)
CREATE TABLE provider_status (
  provider_id text NOT NULL,
  route_class text NOT NULL DEFAULT '',
  state       text NOT NULL DEFAULT 'OPEN'
              CHECK (state IN ('OPEN','PAUSED','HALTED')),
  cause       text,
  not_before  timestamptz,                 -- durable RATE_LIMITED cooldown; PAUSED self-expires
  changed_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (provider_id, route_class)
);

-- §4.4 two-stage admission
CREATE TABLE provider_admission (
  provider_id          text PRIMARY KEY,
  pending_cost         bigint NOT NULL DEFAULT 0,   -- reserved unsatisfied FetchKeys
  pending_cost_limit   bigint NOT NULL,
  unresolved_schedules integer NOT NULL DEFAULT 0,  -- cold-search cap (stage 1)
  unresolved_limit     integer NOT NULL
);
CREATE TABLE admission_reservation (
  search_id   text PRIMARY KEY REFERENCES search,
  provider_id text NOT NULL,
  reserved_total     bigint NOT NULL,      -- validator max (cold) → real count (stage 2)
  -- consumed units must be distinguishable from outstanding ones, or terminalization
  -- releases capacity that satisfaction already released (double release)
  reserved_remaining bigint NOT NULL CHECK (reserved_remaining >= 0),
  released           boolean NOT NULL DEFAULT false
);

CREATE TABLE search_aggregate (            -- nonterminal materialization (§4.1)
  search_id  text PRIMARY KEY REFERENCES search,
  revision   bigint NOT NULL,              -- agg_requested_rev value it satisfied
  payload    jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE search_result_version (       -- immutable terminal result (§4.1 invariant)
  search_id  text NOT NULL REFERENCES search,
  version    integer NOT NULL,
  payload    jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (search_id, version)
);

-- Gate 21 (settled, §7): layout identity is GLOBAL content-addressed
CREATE TABLE auditorium_layout (
  layout_id   text PRIMARY KEY,            -- fingerprint over the FULL input set
  geometry    bytea NOT NULL,
  rows        integer NOT NULL,
  columns     integer NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE layout_occurrence (
  provider_id   text NOT NULL,
  theatre_id    text NOT NULL,
  auditorium    text NOT NULL,
  layout_id     text NOT NULL REFERENCES auditorium_layout,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (provider_id, theatre_id, auditorium, layout_id)
);
